### ISSUE TITLE
Need to group S&P by months

### ISSUE THREAD

**Issue by themarinmuso** [shaf712/fintech-master#15]
We can use this to group by month:

https://pandas.pydata.org/pandas-docs/stable/indexing.html

Slice by date:

https://pandas.pydata.org/pandas-docs/stable/timeseries.html

**Comment by eddc1994** [comment]
Need to extract more data from fundamental data for better analysis

**Comment by themarinmuso** [comment]
I was able to do this using a dictionary and the .loc functionality.
